// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV80Dtyq9IR4MmzgQLNVGeWf0FrHgSL4U',
    appId: '1:856874887595:web:36e0482631b46e764d4aee',
    messagingSenderId: '856874887595',
    projectId: 'travel-planner-61ebc',
    authDomain: 'travel-planner-61ebc.firebaseapp.com',
    storageBucket: 'travel-planner-61ebc.firebasestorage.app',
    measurementId: 'G-V9VH3L7N31',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV80Dtyq9IR4MmzgQLNVGeWf0FrHgSL4U',
    appId: '1:856874887595:web:ce450d9a587f81f04d4aee',
    messagingSenderId: '856874887595',
    projectId: 'travel-planner-61ebc',
    authDomain: 'travel-planner-61ebc.firebaseapp.com',
    storageBucket: 'travel-planner-61ebc.firebasestorage.app',
    measurementId: 'G-R52HXR4Z9G',
  );
}
